#!/bin/bash

pushd $(dirname $0) > /dev/null
basepath=$(pwd)
popd > /dev/null

java -cp $basepath/serverRepartiteur.jar:$basepath/shared.jar -Djava.security.policy=$basepath/policy ca.polymtl.inf4410.tp2.serverRepartiteur.ServerRepartiteur $*